### ISSUE TITLE
Integration of CF7 and LimeDB

### ISSUE THREAD

**Issue by daemonic79** [zaus/forms-3rdparty-integration#37]
Hi,

I see that you had a similar request in #1 some time ago, i was wondering if there was any further info on what hook was required to make it work?

I have my form mappings completed, and have the xpost plugin installed, but not quite sure where to go from here.

I can provide an example from the (limited) docs from limedb and also the debug emails for what i have so far.

**Comment by zaus** [comment]
So regarding that old post -- you can either try the [solution I posted](https://github.com/zaus/forms-3rdparty-integration/issues/1#issuecomment-30588247), which is something I guessed at without having any documentation but has most of the basics, or you can try using the Xpost extension as well to avoid writing code.  Since LimeDB is expecting a SOAP request, as long as it's not too complicated you just need to map your form fields to the XML elements, and maybe add the right header values.

Please post the limedb examples and as much info from the debug emails as you can (don't forget to scrub any sensitive info like accesskeys/passwords before posting).

**Comment by daemonic79** [comment]
Hi Zaus,

I have the xpost installed at the moment, so was hoping to use that if its that easy :)

Do you have an email i can post the examples/debug to?

**Comment by zaus** [comment]
Yeah send it through my website contact form, or post it here.
